---
users:
  users:
    columns:
      email: email
      first_name: first_name
      last_name: last_name
businesses:
  companies:
    columns:
      name: name
    relations:
      user_id:
        new_name: user_id
        rel_table: users
  headquaters:
    group_by: company_id
    columns:
      city: city
      phone1: phone
      street: address_line_1
    relations:
      country_id:
        new_name: country_id
        rel_table: countries
  trading_informations:
    group_by: company_id
    columns:
      year_established: year_registered
products:
  products:
    columns:
      name: name
      description: description
    relations:
      company_id:
        new_name: business_id
        rel_table: businesses
services:
  services:
    columns:
      name: name
      description: description
    relations:
      company_id:
        new_name: business_id
        rel_table: businesses

